[[Food]]
== 음식 API

=== 음식 등록 성공

==== 요청
operation::food-controller-test/success-create-food[snippets='http-request']
operation::food-controller-test/success-create-food[snippets='request-fields']

==== 응답
operation::food-controller-test/success-create-food[snippets='http-response']

=== 음식 등록 실패(식당 NotFound)

==== 요청
operation::food-controller-test/fail-create-food[snippets='http-request']

==== 응답
operation::food-controller-test/fail-create-food[snippets='http-response']

=== 음식 등록 실패(UnAuth)

==== 요청
operation::food-controller-test/fail-create-food-by-un-auth-owner[snippets='http-request']

==== 응답
operation::food-controller-test/fail-create-food-by-un-auth-owner[snippets='http-response']

=== 음식 등록 실패(음식 이름 미입력)

==== 요청
operation::food-controller-test/fail-create-food-by-null-food-name[snippets='http-request']

==== 응답
operation::food-controller-test/fail-create-food-by-null-food-name[snippets='http-response']

=== 음식 등록 실패(음식 가격 미입력)

==== 요청
operation::food-controller-test/fail-create-food-by-null-food-price[snippets='http-request']

==== 응답
operation::food-controller-test/fail-create-food-by-null-food-price[snippets='http-response']

=== 음식 등록 실패(음식 가격 미입력)

==== 요청
operation::food-controller-test/fail-create-food-by-negative-price[snippets='http-request']

==== 응답
operation::food-controller-test/fail-create-food-by-negative-price[snippets='http-response']

=== 음식 목록 조회 성공

==== 요청
operation::food-controller-test/success-find-foods[snippets='http-request']

==== 응답
operation::food-controller-test/success-find-foods[snippets='http-response']
operation::food-controller-test/success-find-foods[snippets='response-fields']

=== 음식 조회 성공

==== 요청
operation::food-controller-test/success-find-food[snippets='http-request']

==== 응답
operation::food-controller-test/success-find-food[snippets='http-response']
operation::food-controller-test/success-find-food[snippets='response-fields']

=== 음식 조회 실패(식당 Notfound)

==== 요청
operation::food-controller-test/fail-find-food-by-not-found-restaurant[snippets='http-request']

==== 응답
operation::food-controller-test/fail-find-food-by-not-found-restaurant[snippets='http-response']

=== 음식 조회 실패(UnAuth)

==== 요청
operation::food-controller-test/fail-find-food-by-un-auth[snippets='http-request']

==== 응답
operation::food-controller-test/fail-find-food-by-un-auth[snippets='http-response']
