[[Order]]
== 주문 API

=== 주문 생성 성공

==== 요청
operation::order-controller-test/success-create-order[snippets='http-request']
operation::order-controller-test/success-create-order[snippets='request-fields']

==== 응답
operation::order-controller-test/success-create-order[snippets='http-response']

=== 주문 생성 실패(식당 NotFound)

==== 요청
operation::order-controller-test/fail-create-order[snippets='http-request']

==== 응답
operation::order-controller-test/fail-create-order[snippets='http-response']

=== 주문 생성 실패(메뉴 NotFound)

==== 요청
operation::order-controller-test/fail-create-order-by-not-found-menu[snippets='http-request']

==== 응답
operation::order-controller-test/fail-create-order-by-not-found-menu[snippets='http-response']

=== 주문 조회 성공

==== 요청
operation::order-controller-test/success-find-order[snippets='http-request']

==== 응답
operation::order-controller-test/success-find-order[snippets='http-response']
operation::order-controller-test/success-find-order[snippets='response-fields']

=== 주문 조회 실패(주문 Not Found)

==== 요청
operation::order-controller-test/fail-find-order-by-not-found-order[snippets='http-request']

==== 응답
operation::order-controller-test/fail-find-order-by-not-found-order[snippets='http-response']

=== 전화번호를 통한 주문 목록 조회 성공

==== 요청
operation::order-controller-test/success-find-orders-by-phone[snippets='http-request']

==== 응답
operation::order-controller-test/success-find-orders-by-phone[snippets='http-response']
operation::order-controller-test/success-find-orders-by-phone[snippets='response-fields']
