[[Owner]]
== 식당 주인 API

=== 회원가입 성공

==== 요청
operation::owner-controller-test/success-join[snippets='http-request']
operation::owner-controller-test/success-join[snippets='request-fields']

==== 응답
operation::owner-controller-test/success-join[snippets='http-response']

=== 회원가입 실패(아이디 중복)

==== 요청
operation::owner-controller-test/fail-join-by-duplicate-identifier[snippets='http-request']

==== 응답
operation::owner-controller-test/fail-join-by-duplicate-identifier[snippets='http-response']

=== 회원가입 실패(아이디 형식)

==== 요청
operation::owner-controller-test/fail-join-by-valid-identifier[snippets='http-request']

==== 응답
operation::owner-controller-test/fail-join-by-valid-identifier[snippets='http-response']

=== 회원가입 실패(비밀번호 형식)

==== 요청
operation::owner-controller-test/fail-join-by-valid-password[snippets='http-request']

==== 응답
operation::owner-controller-test/fail-join-by-valid-password[snippets='http-response']

=== 회원가입 실패(아이디 미입력)

==== 요청
operation::owner-controller-test/fail-join-by-empty-identifier[snippets='http-request']

==== 응답
operation::owner-controller-test/fail-join-by-empty-identifier[snippets='http-response']

=== 회원가입 실패(비밀번호 미입력)

==== 요청
operation::owner-controller-test/fail-join-by-empty-password[snippets='http-request']

==== 응답
operation::owner-controller-test/fail-join-by-empty-password[snippets='http-response']
